// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using NoBullshit.Server.Data;

#nullable disable

namespace NoBullshit.Server.Migrations
{
    [DbContext(typeof(NoBullshitContext))]
    [Migration("20211025065229_InitialCreate")]
    partial class InitialCreate
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "6.0.0-rc.2.21480.5");

            modelBuilder.Entity("NoBullshit.Shared.Models.Game", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Added")
                        .HasColumnType("TEXT");

                    b.Property<string>("Genres")
                        .HasColumnType("TEXT");

                    b.Property<string>("ImageUrl")
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .HasColumnType("TEXT");

                    b.Property<string>("Platform")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<decimal>("Price")
                        .HasColumnType("TEXT");

                    b.Property<float>("Rating")
                        .HasColumnType("REAL");

                    b.Property<int>("Reviews")
                        .HasColumnType("INTEGER");

                    b.Property<string>("StoreUrl")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Games");

                    b.HasDiscriminator<string>("Platform").HasValue("Game");
                });

            modelBuilder.Entity("NoBullshit.Shared.Models.AndroidGame", b =>
                {
                    b.HasBaseType("NoBullshit.Shared.Models.Game");

                    b.HasDiscriminator().HasValue("android");
                });

            modelBuilder.Entity("NoBullshit.Shared.Models.IOSGame", b =>
                {
                    b.HasBaseType("NoBullshit.Shared.Models.Game");

                    b.HasDiscriminator().HasValue("ios");
                });
#pragma warning restore 612, 618
        }
    }
}
